version: '3'

services:
  nginx:
    image: nginx:1.20-alpine
    container_name: blog-nginx
    ports:
      - "8080:80"
    working_dir: /srv/web
    volumes:
      - ./.docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./:/srv/web
    depends_on:
      - php
      - mysql
    networks:
      - blog-network

  php:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: blog-php
    working_dir: /srv/web
    volumes:
      - ./:/srv/web
      - ${HOME}/.composer:${HOME}/.composer
    extra_hosts:
      - "blog.local:127.0.0.1"
    networks:
      - blog-network

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: blog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: secret
    volumes:
      - ./.docker/data:/var/lib/mysql
    ports:
        - "3306:3306"
    networks:
      - blog-network

  phpmyadmin:
    image: phpmyadmin:5.0
    container_name: blog-phpmyadmin
    environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
    restart: always
    ports:
        - "8000:80"
    networks:
        - blog-network

networks:
  blog-network:
    driver: bridge
